version: 2.0.0-alpha{build}
branches:
  only:
  - master
  - develop
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- choco install msbuild.communitytasks -y
build:
  project: build.msbuild
  verbosity: normal
artifacts:
- path: build/package/**/*.nupkg
  name: NuGet Package
- path: build/package/**/*.zip
  name: Zip Archive
deploy:
- provider: NuGet
  api_key:
    secure: fnfp0KvYrSJ4VETGtf4WyajYJnyKVIQsde+8uzQ42ERjcSPpCfX9fYlqrK3kHEp5
  artifact: /.*\.nupkg/